version: '2'

services:
  mongodb:
    container_name: mongo
    image: docker.io/bitnami/mongodb:4.2
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-data:/bitnami/mongodb'
    networks: 
      - parse-network
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_USERNAME=parse
      - MONGODB_DATABASE=parse
      - MONGODB_PASSWORD=parse
      - MONGODB_ROOT_PASSWORD=parse
    
  parse:
    container_name: parse-server
    image: docker.io/bitnami/parse:4
    ports:
      - '1337:1337'
    volumes:
      - 'parse-data:/bitnami/parse'
    depends_on:
      - mongodb
    networks: 
      - parse-network
    environment:
      - PARSE_DATABASE_HOST=mongodb
      - PARSE_DATABASE_PORT_NUMBER=27017
      - PARSE_DATABASE_USER=parse
      - PARSE_DATABASE_NAME=parse
      - PARSE_DATABASE_PASSWORD=parse

  parse-dashboard:
    container_name: parse-dashboard
    image: docker.io/bitnami/parse-dashboard:3
    ports:
      - '4040:4040'
    volumes:
      - 'parse-dashboard-data:/bitnami'
    depends_on:
      - parse
    networks: 
      - parse-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    ports: 
      - '8081:8081'
    depends_on:
      - mongodb
    networks: 
      - parse-network
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=parse

volumes:
  mongo-data:
    driver: local
  parse-data:
    driver: local
  parse-dashboard-data:
    driver: local

networks:
  parse-network:
    driver: bridge